export const mockPipelineData = {
  totalPipeline: 45200,
  weightedPipeline: 18400,

  stages: [
    { stage: "Lead", count: 28, value: 8400, probability: 10 },
    { stage: "Contacted", count: 15, value: 7500, probability: 20 },
    { stage: "Meeting Booked", count: 8, value: 6400, probability: 35 },
    { stage: "Demo Completed", count: 6, value: 5400, probability: 50 },
    { stage: "Proposal Sent", count: 4, value: 7200, probability: 65 },
    { stage: "Trial Started", count: 3, value: 5400, probability: 75 },
    { stage: "Negotiation", count: 2, value: 3600, probability: 85 },
    { stage: "Closed Won", count: 12, value: 10800, probability: 100 },
    { stage: "Closed Lost", count: 9, value: 4500, probability: 0 },
  ],

  deals: [
    { id: "d1", companyName: "Groene Tafel Amsterdam", dealName: "Loyalty Wallet - Basic", stage: "Lead", value: 1068, expectedMrr: 89, probability: 10, source: "Cold Email", partnerOwner: "Carlo", closeDate: "2026-01-15" },
    { id: "d2", companyName: "Sabor Natural Seville", dealName: "Loyalty Wallet - Spain", stage: "Contacted", value: 588, expectedMrr: 49, probability: 20, source: "HIP Spain", partnerOwner: "Joaquin", closeDate: "2026-01-10" },
    { id: "d3", companyName: "Plant Base Rotterdam", dealName: "Wallet + Email", stage: "Meeting Booked", value: 1068, expectedMrr: 89, probability: 35, source: "LinkedIn", partnerOwner: "Niels", closeDate: "2026-01-20" },
    { id: "d4", companyName: "Biocenter Antwerp", dealName: "Loyalty Wallet - Basic", stage: "Demo Completed", value: 1068, expectedMrr: 89, probability: 50, source: "Cold Calling", partnerOwner: "Dorian", closeDate: "2026-02-01" },
    { id: "d5", companyName: "EcoEat Bogotá", dealName: "Colombia Plan", stage: "Proposal Sent", value: 348, expectedMrr: 29, probability: 65, source: "Colombia", partnerOwner: "Jonathan", closeDate: "2025-12-28" },
    { id: "d6", companyName: "Madre Natura Torino", dealName: "Italy Standard", stage: "Trial Started", value: 588, expectedMrr: 49, probability: 75, source: "Italy Outbound", partnerOwner: "Carlo", closeDate: "2025-12-20" },
    { id: "d7", companyName: "Green Garden Den Haag", dealName: "Wallet + Winback", stage: "Negotiation", value: 1068, expectedMrr: 89, probability: 85, source: "Horecava", partnerOwner: "Giuseppe", closeDate: "2025-12-15" },
    { id: "d8", companyName: "Veggie World Leiden", dealName: "Loyalty Wallet", stage: "Lead", value: 1068, expectedMrr: 89, probability: 10, source: "Cold Calling", partnerOwner: "Dorian", closeDate: "2026-02-15" },
    { id: "d9", companyName: "Organic Hub Madrid", dealName: "Spain Basic", stage: "Meeting Booked", value: 588, expectedMrr: 49, probability: 35, source: "Spain Outbound", partnerOwner: "Joaquin", closeDate: "2026-01-25" },
    { id: "d10", companyName: "The Plant Bar Utrecht", dealName: "Full Suite", stage: "Contacted", value: 1068, expectedMrr: 89, probability: 20, source: "Website", partnerOwner: "Giuseppe", closeDate: "2026-02-10" },
    { id: "d11", companyName: "Floresta Viva Lisbon", dealName: "Wallet Basic", stage: "Demo Completed", value: 588, expectedMrr: 49, probability: 50, source: "Referral", partnerOwner: "Giuseppe", closeDate: "2026-01-18" },
    { id: "d12", companyName: "Kale & Roots Eindhoven", dealName: "Loyalty + Notifications", stage: "Proposal Sent", value: 1068, expectedMrr: 89, probability: 65, source: "LinkedIn", partnerOwner: "Niels", closeDate: "2025-12-30" },
    { id: "d13", companyName: "Qubico Restaurant Group", dealName: "Agency White Label", stage: "Trial Started", value: 2136, expectedMrr: 178, probability: 75, source: "Qubico Studio", partnerOwner: "Qubico Studio", closeDate: "2025-12-22" },
    { id: "d14", companyName: "Vegano Milano", dealName: "Italy Standard", stage: "Lead", value: 588, expectedMrr: 49, probability: 10, source: "Italy Outbound", partnerOwner: "Carlo", closeDate: "2026-02-20" },
    { id: "d15", companyName: "Broccoli Bar Groningen", dealName: "Wallet Basic", stage: "Contacted", value: 1068, expectedMrr: 89, probability: 20, source: "Cold Email", partnerOwner: "Carlo", closeDate: "2026-02-05" },
    { id: "d16", companyName: "CitySales Demo NL", dealName: "CitySales Bundle", stage: "Meeting Booked", value: 2136, expectedMrr: 178, probability: 35, source: "CitySales", partnerOwner: "Giuseppe", closeDate: "2026-01-30" },
    { id: "d17", companyName: "Naturaleza Cali", dealName: "Colombia Starter", stage: "Lead", value: 348, expectedMrr: 29, probability: 10, source: "Colombia", partnerOwner: "Jonathan", closeDate: "2026-02-28" },
    { id: "d18", companyName: "The Herbivore Brussels", dealName: "Wallet Pro", stage: "Demo Completed", value: 1068, expectedMrr: 89, probability: 50, source: "Cold Email", partnerOwner: "Dorian", closeDate: "2026-01-28" },
    { id: "d19", companyName: "Verde Gourmet Barcelona", dealName: "Spain Standard", stage: "Negotiation", value: 588, expectedMrr: 49, probability: 85, source: "HIP Spain", partnerOwner: "Joaquin", closeDate: "2025-12-18" },
    { id: "d20", companyName: "OptiDist Partner", dealName: "Distribution Deal", stage: "Proposal Sent", value: 3204, expectedMrr: 267, probability: 65, source: "OptiDist", partnerOwner: "Giuseppe", closeDate: "2026-01-08" },
  ],
};
