export const mockRevenueData = {
  currentMRR: 1400,
  arr: 16800,
  growth: 12.5,
  churn: 2.1,
  netRevenue: 1350,
  newMRR: 280,
  churnedMRR: 80,
  expansionMRR: 50,
  activeClients: 32,
  averageRevenuePerClient: 43.75,

  mrrHistory: [
    { month: "Jan 2025", mrr: 800 },
    { month: "Feb 2025", mrr: 860 },
    { month: "Mar 2025", mrr: 920 },
    { month: "Apr 2025", mrr: 980 },
    { month: "May 2025", mrr: 1020 },
    { month: "Jun 2025", mrr: 1080 },
    { month: "Jul 2025", mrr: 1120 },
    { month: "Aug 2025", mrr: 1160 },
    { month: "Sep 2025", mrr: 1220 },
    { month: "Oct 2025", mrr: 1280 },
    { month: "Nov 2025", mrr: 1340 },
    { month: "Dec 2025", mrr: 1400 },
  ],

  clients: [
    { id: "c1", name: "Brasserie De Kade", country: "NL", mrr: 89, status: "active", startDate: "2025-01-15", source: "Horecava", partnerOwner: "Giuseppe" },
    { id: "c2", name: "Grand Café Centraal", country: "NL", mrr: 89, status: "active", startDate: "2025-02-01", source: "Cold Calling", partnerOwner: "Dorian" },
    { id: "c3", name: "El Patio Madrid", country: "ES", mrr: 49, status: "active", startDate: "2025-03-10", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c4", name: "Café Hoorn", country: "NL", mrr: 89, status: "active", startDate: "2025-01-20", source: "Referral", partnerOwner: "Giuseppe" },
    { id: "c5", name: "Restaurant Zuidas", country: "NL", mrr: 49, status: "trial", startDate: "2025-11-01", source: "LinkedIn", partnerOwner: "Niels" },
    { id: "c6", name: "La Terraza Barcelona", country: "ES", mrr: 49, status: "active", startDate: "2025-04-05", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c7", name: "Eetcafé De Zon", country: "NL", mrr: 89, status: "active", startDate: "2025-02-14", source: "Cold Email", partnerOwner: "Carlo" },
    { id: "c8", name: "Stadsbrouwerij Utrecht", country: "NL", mrr: 89, status: "active", startDate: "2025-03-22", source: "Horecava", partnerOwner: "Giuseppe" },
    { id: "c9", name: "Taberna Central Bogotá", country: "CO", mrr: 29, status: "active", startDate: "2025-05-01", source: "Colombia", partnerOwner: "Jonathan" },
    { id: "c10", name: "Trattoria Lombarda Milan", country: "IT", mrr: 49, status: "active", startDate: "2025-06-01", source: "Italy Outbound", partnerOwner: "Carlo" },
    { id: "c11", name: "Havana Club Rotterdam", country: "NL", mrr: 89, status: "active", startDate: "2025-04-18", source: "Cold Calling", partnerOwner: "Dorian" },
    { id: "c12", name: "Bodega Valencia", country: "ES", mrr: 49, status: "churned", startDate: "2025-02-01", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c13", name: "Skybar Den Haag", country: "NL", mrr: 89, status: "active", startDate: "2025-07-10", source: "LinkedIn", partnerOwner: "Niels" },
    { id: "c14", name: "Café Bogotá Centro", country: "CO", mrr: 29, status: "active", startDate: "2025-08-01", source: "Colombia", partnerOwner: "Jonathan" },
    { id: "c15", name: "Qubico Demo Venue", country: "NL", mrr: 89, status: "trial", startDate: "2025-11-15", source: "Qubico Studio", partnerOwner: "Qubico Studio" },
    { id: "c16", name: "Gym & Sports Club Breda", country: "NL", mrr: 89, status: "active", startDate: "2025-07-01", source: "Cold Email", partnerOwner: "Giuseppe" },
    { id: "c17", name: "Fitness Center Eindhoven", country: "NL", mrr: 49, status: "active", startDate: "2025-08-15", source: "Referral", partnerOwner: "Dorian" },
    { id: "c18", name: "Barbershop Jordaan", country: "NL", mrr: 49, status: "active", startDate: "2025-09-01", source: "LinkedIn", partnerOwner: "Niels" },
    { id: "c19", name: "Nail Studio Vondelpark", country: "NL", mrr: 49, status: "active", startDate: "2025-09-15", source: "Cold Email", partnerOwner: "Carlo" },
    { id: "c20", name: "Snackbar De Hoek", country: "NL", mrr: 29, status: "active", startDate: "2025-10-01", source: "Referral", partnerOwner: "Giuseppe" },
  ],

  revenueByCountry: [
    { country: "Netherlands", mrr: 890, clients: 14 },
    { country: "Spain", mrr: 245, clients: 5 },
    { country: "Colombia", mrr: 116, clients: 4 },
    { country: "Italy", mrr: 98, clients: 2 },
    { country: "Other", mrr: 51, clients: 7 },
  ],

  revenueBySegment: [
    { segment: "Restaurant / Café", mrr: 712, clients: 18 },
    { segment: "Gym / Sports", mrr: 178, clients: 4 },
    { segment: "Beauty / Wellness", mrr: 178, clients: 6 },
    { segment: "Retail / Shop", mrr: 89, clients: 3 },
    { segment: "Trial / Other", mrr: 243, clients: 7 },
  ],
};
