export const mockRevenueData = {
  currentMRR: 1400,
  arr: 16800,
  growth: 12.5,
  churn: 2.1,
  netRevenue: 1350,
  newMRR: 280,
  churnedMRR: 80,
  expansionMRR: 50,
  activeClients: 32,
  averageRevenuePerClient: 43.75,

  mrrHistory: [
    { month: "Jan 2025", mrr: 800 },
    { month: "Feb 2025", mrr: 860 },
    { month: "Mar 2025", mrr: 920 },
    { month: "Apr 2025", mrr: 980 },
    { month: "May 2025", mrr: 1020 },
    { month: "Jun 2025", mrr: 1080 },
    { month: "Jul 2025", mrr: 1120 },
    { month: "Aug 2025", mrr: 1160 },
    { month: "Sep 2025", mrr: 1220 },
    { month: "Oct 2025", mrr: 1280 },
    { month: "Nov 2025", mrr: 1340 },
    { month: "Dec 2025", mrr: 1400 },
  ],

  clients: [
    { id: "c1", name: "De Groenhoek", country: "NL", mrr: 89, status: "active", startDate: "2025-01-15", source: "Horecava", partnerOwner: "Giuseppe" },
    { id: "c2", name: "Vega Kitchen Amsterdam", country: "NL", mrr: 89, status: "active", startDate: "2025-02-01", source: "Cold Calling", partnerOwner: "Dorian" },
    { id: "c3", name: "El Vergel Madrid", country: "ES", mrr: 49, status: "active", startDate: "2025-03-10", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c4", name: "Roots & Co", country: "NL", mrr: 89, status: "active", startDate: "2025-01-20", source: "Referral", partnerOwner: "Giuseppe" },
    { id: "c5", name: "Green Elephant", country: "NL", mrr: 49, status: "trial", startDate: "2025-11-01", source: "LinkedIn", partnerOwner: "Niels" },
    { id: "c6", name: "La Floresta Barcelona", country: "ES", mrr: 49, status: "active", startDate: "2025-04-05", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c7", name: "Plantiful Haarlem", country: "NL", mrr: 89, status: "active", startDate: "2025-02-14", source: "Cold Email", partnerOwner: "Carlo" },
    { id: "c8", name: "Bio Bistro Utrecht", country: "NL", mrr: 89, status: "active", startDate: "2025-03-22", source: "Horecava", partnerOwner: "Giuseppe" },
    { id: "c9", name: "Madre Tierra Bogotá", country: "CO", mrr: 29, status: "active", startDate: "2025-05-01", source: "Colombia", partnerOwner: "Jonathan" },
    { id: "c10", name: "Naturverde Milan", country: "IT", mrr: 49, status: "active", startDate: "2025-06-01", source: "Italy Outbound", partnerOwner: "Carlo" },
    { id: "c11", name: "The Sprout Rotterdam", country: "NL", mrr: 89, status: "active", startDate: "2025-04-18", source: "Cold Calling", partnerOwner: "Dorian" },
    { id: "c12", name: "Vegano Valencia", country: "ES", mrr: 49, status: "churned", startDate: "2025-02-01", source: "HIP Spain", partnerOwner: "Joaquin" },
    { id: "c13", name: "Conscious Kitchen Den Haag", country: "NL", mrr: 89, status: "active", startDate: "2025-07-10", source: "LinkedIn", partnerOwner: "Niels" },
    { id: "c14", name: "Pura Vida Medellín", country: "CO", mrr: 29, status: "active", startDate: "2025-08-01", source: "Colombia", partnerOwner: "Jonathan" },
    { id: "c15", name: "Qubico Demo Client", country: "NL", mrr: 89, status: "trial", startDate: "2025-11-15", source: "Qubico Studio", partnerOwner: "Qubico Studio" },
  ],

  revenueByCountry: [
    { country: "Netherlands", mrr: 890, clients: 14 },
    { country: "Spain", mrr: 245, clients: 5 },
    { country: "Colombia", mrr: 116, clients: 4 },
    { country: "Italy", mrr: 98, clients: 2 },
    { country: "Other", mrr: 51, clients: 7 },
  ],

  revenueBySegment: [
    { segment: "Independent Restaurant", mrr: 712, clients: 18 },
    { segment: "Chain / Group", mrr: 356, clients: 6 },
    { segment: "Dark Kitchen", mrr: 178, clients: 4 },
    { segment: "Catering", mrr: 89, clients: 2 },
    { segment: "Trial", mrr: 65, clients: 2 },
  ],
};
